class_name Descriptions
extends Reference


# FIXME: ---------------- Add better descriptions.

const SHORT := {
    BOT_CONSTRUCTOR = "BOT_CONSTRUCTOR",
    BOT_LINE_RUNNER = "BOT_LINE_RUNNER",
    BOT_REPAIR = "BOT_REPAIR",
    BOT_BARRIER = "BOT_BARRIER",
    BOT_COMMAND = "BOT_COMMAND",
    BOT_STOP = "BOT_STOP",
    BOT_MOVE = "BOT_MOVE",
    BOT_RECYCLE = "BOT_RECYCLE",
    BOT_INFO = "BOT_INFO",

    STATION_COMMAND = "STATION_COMMAND",
    STATION_SOLAR = "STATION_SOLAR",
    STATION_SCANNER = "STATION_SCANNER",
    STATION_BATTERY = "STATION_BATTERY",
    STATION_RECYCLE = "STATION_RECYCLE",
    STATION_INFO = "STATION_INFO",

    RUN_WIRE = "RUN_WIRE",
}

const VERBOSE := {
    BOT_CONSTRUCTOR = "BOT_CONSTRUCTOR",
    BOT_LINE_RUNNER = "BOT_LINE_RUNNER",
    BOT_REPAIR = "BOT_REPAIR",
    BOT_BARRIER = "BOT_BARRIER",
    BOT_COMMAND = "BOT_COMMAND",
    BOT_STOP = "BOT_STOP",
    BOT_MOVE = "BOT_MOVE",
    BOT_RECYCLE = "BOT_RECYCLE",
    BOT_INFO = "BOT_INFO",

    STATION_COMMAND = "STATION_COMMAND",
    STATION_SOLAR = "STATION_SOLAR",
    STATION_SCANNER = "STATION_SCANNER",
    STATION_BATTERY = "STATION_BATTERY",
    STATION_RECYCLE = "STATION_RECYCLE",
    STATION_INFO = "STATION_INFO",

    RUN_WIRE = "RUN_WIRE",
}

